#!/usr/bin/sh
# Install sway and desktop programs

sudo pacman -S --noconfirm \
	rsync \
	polkit \
	light \
	alsa-utils \
	sway \
	xdg-utils \
	xdg-desktop-portal-wlr \
	libnotify \
	swayidle \
	swaybg \
	waylock \
	waybar \
	wtype \
	wl-clipboard \
	grim \
	slurp \
	alacritty \
	mpv \
	imv \
	pavucontrol \
	firefox \
	zathura \
	zathura-pdf-poppler \
	ttf-hack \
	gnu-free-fonts \
	noto-fonts \
	noto-fonts-emoji \
	noto-fonts-cjk \
	gnome-keyring-daemon \
